#!/bin/sh

function relink() {
	[ -e $1 ] && rm -i $1
	ln -sfn $2 $1
}

cd ~
for f in ~/dotfiles/.*; do 
	base=`basename $f`
	case "$base" in
		.|..|mkln|.git|.gitignore) continue;;
	esac
	relink $base $f
done
