#!/bin/sh

alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -lh'
alias l='ls  $LS_OPTIONS -lAh'
alias la='ls $LS_OPTIONS -lah'
alias df='df -h'

alias esx='exec screen -x'
alias essh='exec ssh'
alias j=jobs
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias pu="pushd"
alias po="popd"
alias c='reset; stty sane; tput rs1; clear; echo -ne "\033c"'
alias pps='ps -u "$USER" -o user,pid,ppid,pcpu,pmem,args'
alias dums='du -ms -- * | sort -n'
alias h=history
alias q=exit
alias mtr="mtr --curses"
alias grep="grep --color=auto --exclude '*.git*' --exclude '*.svn*' --exclude '*.sw?'"
alias s="sudo"
alias be="bundle exec"
alias rmswp="find . -name *.swp -a -type f | xargs rm "
alias sshsocks="ssh -fCND 1080 "
alias clear_colors='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"'
alias pathbin='export PATH="$PWD/bin:$PATH"' # Useful for bundler binstubs
alias apt='sudo apt'
alias apti='sudo apt install'
alias apts='apt search'
alias G='gnome-open'

# network
alias show-tcp-listen='sudo netstat -pant|grep LISTEN'
alias ipaddr="ip addr | awk '/^[0-9]+/ { curriface=\$2 } \$1 == \"inet\" { split( \$2, foo, \"/\" ); print curriface ,foo[1] }'" # pretty ip addr

# docker
alias d='sudo docker'
alias dl='sudo docker ps -l -q' # docker latest container
alias dockviz="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz"
alias dc='docker-compose'
alias dce='docker-compose exec '
alias dclf='docker-compose logs -f --tail=100'
alias dcrm='docker-compose rm -sf'
alias dockc='docker-compose'
alias dockps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}"'
alias dockports='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}"'
alias dockexecl='docker exec -i -t $(docker ps -l -q) /bin/bash'

alias sen='docker run -v /run/docker.sock:/run/docker.sock -ti -e TERM tomastomecek/sen'
alias docker-rm-unused-images='docker images --filter "dangling=true" -q --no-trunc | xargs --no-run-if-empty docker rmi'
alias docker-rm-unused-volumes='docker volume rm $(docker volume ls -qf dangling=true)'
alias docker-rm-stopped-containers='docker ps --filter "status=exited" -q --no-trunc | xargs --no-run-if-empty docker rm'
alias k='kubectl'
alias kcompl="source <(kubectl completion bash)"


# systemd
alias sc='sudo systemctl'
alias sctl='sudo systemctl'
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias restart='sudo systemctl restart'
alias status='sudo systemctl status'

# clipboard copy
alias pbcopy="xclip -sel clip"


inspath(){
  if [ -d "$1" ]; then
    export PATH="$1:$PATH"
  fi
}
addpath(){
  if [ -d "$1" ]; then
    export PATH="$PATH:$1"
  fi
}
