#!/bin/sh

alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -lh'
alias l='ls  $LS_OPTIONS -lAh'
alias la='ls $LS_OPTIONS -lah'
alias df='df -h'

alias esx='exec screen -x'
alias essh='exec ssh'
alias j=jobs
alias ..="cd .."
alias pu="pushd"
alias po="popd"
alias c='reset; stty sane; tput rs1; clear; echo -ne "\033c"'
alias pps='ps -u "$USER" -o user,pid,ppid,pcpu,pmem,args'
alias dums='du -ms * | sort -n'
alias h=history
alias q=exit
alias mtr="mtr --curses"
alias grep="grep --color=auto --exclude '*.git*' --exclude '*.svn*' --exclude '*.sw?'"
alias s="sudo"
alias be="bundle exec"
alias rmswp="find . -name *.swp -a -type f | xargs rm "
alias sshsocks="ssh -fCND 1080 "
alias clear_colors='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"'
alias pathbin='export PATH="$PWD/bin:$PATH"' # Useful for bundler binstubs
alias apti='sudo apt install'
alias apts='apt search'
alias G='gnome-open'


# docker
alias d='sudo docker'
alias dl='sudo docker ps -l -q' # docker latest container
alias dockviz="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz"
alias sen='docker run -v /run/docker.sock:/run/docker.sock -ti -e TERM tomastomecek/sen'
alias docker-rm-unused-images='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias docker-rm-unused-volumes='docker volume rm $(docker volume ls -qf dangling=true)'
if [ -x "`which kubectl 2>/dev/null`" ]; then
  alias k='kubectl'
  source <(kubectl completion bash)
fi


# systemd
alias sc='sudo systemctl'
alias sctl='sudo systemctl'
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias restart='sudo systemctl restart'


inspath(){
  if [ -d "$1" ]; then
    export PATH="$1:$PATH"
  fi
}
addpath(){
  if [ -d "$1" ]; then
    export PATH="$PATH:$1"
  fi
}
